services:
  leap_compliance:
    build:
      context: .
      dockerfile: Dockerfile
    image: leap-compliance-mcc:latest
    container_name: leap_compliance_mcc
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./leap_hand:/catkin_ws/src/leap_hand
      - ./leap_description:/catkin_ws/src/leap_description
      - ./vendor/mcc:/opt/mcc
    environment:
      - MCC_ROOT=/opt/mcc
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: bash
